import test from 'node:test';
import assert from 'node:assert/strict';
import {Puzzle} from '../src/model.js';
import {levels,tutorial} from '../src/levels.js';
function wait(p,s){for(let i=0;i<s*60;i++)p.tick(1/60)}
for(const l of [tutorial,...levels])test(`${l.id}. ${l.name}: solution opens portal`,()=>{const p=new Puzzle(l);for(const a of l.solution){if(a.id)for(let i=0;i<a.n;i++){wait(p,.5);assert.ok(p.move(a.id,a.dx,a.dz),`blocked ${a.id}: ${a.dx},${a.dz}`);}if(a.rotate)assert.ok(p.rotate(a.rotate));if(a.record!==undefined)p.toggleRecord();if(a.play)assert.ok(p.play());if(a.wait)wait(p,a.wait);p.evaluate();}assert.ok(p.ready,JSON.stringify(p.flags));});
test('linked pair is atomic when either cube is blocked',()=>{const p=new Puzzle(levels[4]),s=JSON.stringify(p.cubes);assert.equal(p.move('l1',0,-1),false);assert.equal(JSON.stringify(p.cubes),s);assert.ok(p.move('l1',-1,0));assert.equal(p.cubes[1].x,3);assert.ok(p.undo());assert.equal(JSON.stringify(p.cubes),s);});
test('cube cannot leave island or overlap another cube',()=>{const p=new Puzzle(tutorial);for(let i=0;i<3;i++)p.move('m',1,0);assert.equal(p.move('m',1,0),false);const q=new Puzzle(levels[1]);assert.ok(q.move('a',1,0));assert.ok(q.move('a',1,0));assert.ok(q.move('a',1,0));assert.equal(q.move('a',1,0),false);});
test('phase wall and bridge switch together',()=>{const p=new Puzzle(levels[5]);assert.ok(p.isWall(0,-1));assert.equal(p.floor(0,-3),null);p.move('m',-1,0);p.move('m',0,-1);p.move('m',0,-1);assert.equal(p.isWall(0,-1),false);assert.ok(p.floor(0,-3));});
test('echo remembers, loops, resets and supports undo',()=>{const p=new Puzzle(levels[6]);p.toggleRecord();wait(p,.5);p.move('e',0,-1);wait(p,.5);p.move('e',0,-1);p.toggleRecord();assert.ok(p.play());wait(p,1.1);assert.ok(p.flags.pulseA);wait(p,5.1);assert.equal(p.cubes[0].z,2);p.resetEcho();assert.equal(p.echo.events.length,0);assert.equal(p.echo.playing,false);assert.ok(p.undo());assert.equal(p.echo.events.length,2);});
test('conductor requires cardinal adjacency and optical phase blocks ray',()=>{const p=new Puzzle(levels[7]);assert.equal(p.flags.power,false);for(const a of levels[7].solution.slice(0,3))for(let i=0;i<a.n;i++)p.move(a.id,a.dx,a.dz);assert.ok(p.flags.power);p.move('r',0,-1);p.move('r',0,-1);p.rotate('r');assert.equal(p.flags.light,false);p.move('m',1,0);for(let i=0;i<3;i++)p.move('m',0,-1);assert.ok(p.flags.light);});
