const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/codex/cua_node/lib/node_modules/playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const errors=[];fs.mkdirSync('.artifacts',{recursive:true});if(!process.argv.includes('--layouts-only')){
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173/?qa',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__rift);fs.mkdirSync('.artifacts',{recursive:true});
 // Real portal entry must update progression, show a continuation at 10 and
 // celebrate only after 30. Pure-model and Player route tests run separately.
 for(let id=1;id<=30;id++){await page.evaluate(id=>{__rift.start(id);const m=__rift.model;m.canReplay=null;for(const a of m.level.solution){if(a.id)for(let i=0;i<a.n;i++){for(let j=0;j<30;j++)m.tick(1/60);if(!m.move(a.id,a.dx,a.dz))throw Error('blocked solution '+id);}if(a.rotate)m.rotate(a.rotate);if(a.record!==undefined)m.toggleRecord();if(a.play)m.play();if(a.wait)for(let i=0;i<a.wait*60;i++)m.tick(1/60);}if(!m.ready)throw Error('not ready '+id);__rift.player.release();__rift.player.pos.set(m.level.portal[0]*2,m.height(...m.level.portal),m.level.portal[1]*2);},id);await page.waitForFunction(()=>window.__rift?.state==='complete');if(id===10){assert.equal(await page.locator('#modal-buttons button').first().textContent(),'Следующий остров');assert.equal(await page.evaluate(()=>__rift.saved.unlocked),11);}if(id===30){assert.equal(await page.locator('#modal-title').textContent(),'Свет вернулся.');assert.ok(await page.evaluate(()=>!!__rift.world.celebration));await page.screenshot({path:'.artifacts/ending-30.png'});}console.log('PASS campaign portal '+id);}
 assert.equal(await page.evaluate(()=>__rift.saved.completed.length),30);await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>__rift.saved.unlocked),30);assert.equal(await page.evaluate(()=>__rift.saved.current),30);assert.equal(await page.locator('#levels .level-button').first().getAttribute('aria-label'),'Уровень 21: Энергетическое дерево');for(const [act,first]of[[0,1],[1,11],[2,21]]){await page.locator('#act-tabs button').nth(act).click();assert.equal(await page.locator('.level-button').count(),10);assert.equal(await page.locator('.level-button:disabled').count(),0);assert.ok((await page.locator('.level-button').first().getAttribute('aria-label')).startsWith('Уровень '+first+':'));}assert.ok(await page.evaluate(()=>{const a=document.querySelector('#tutorial').getBoundingClientRect(),b=document.querySelector('.level-dock').getBoundingClientRect();return a.bottom<b.top;}),'desktop menu overlaps the dock');await page.screenshot({path:'.artifacts/menu-30-desktop.png'});
 await page.evaluate(()=>localStorage.setItem('rift-cubes-v1',JSON.stringify({unlocked:10,current:10,completed:[1,2,3,4,5,6,7,8,9,10],volume:0,sensitivity:1.7,quality:'low'})));await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>__rift.saved.current),11);assert.equal(await page.evaluate(()=>__rift.saved.unlocked),11);assert.equal(await page.evaluate(()=>__rift.saved.volume),0);assert.equal(await page.evaluate(()=>__rift.saved.sensitivity),1.7);await page.click('#play');await page.waitForFunction(()=>__rift.state==='playing'&&__rift.model.level.id===11);await page.keyboard.press('KeyM');assert.equal(await page.evaluate(()=>__rift.state),'map');assert.ok(await page.locator('#island-map').isVisible());await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>__rift.state),'playing');console.log('PASS 3 acts, old save migration, map and final after island 30');
 await page.close();}
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true}),phone=await context.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto('http://localhost:5173/?qa',{waitUntil:'networkidle'});await phone.evaluate(()=>{__rift.saved.unlocked=30;__rift.saved.current=30;__rift.saved.quality='low';__rift.save();});await phone.reload({waitUntil:'networkidle'});console.log('Phone page after reload:',await phone.evaluate(()=>({url:location.href,play:!!document.querySelector('#play'),state:window.__rift?.state,loading:document.querySelector('#loading')?.textContent})));await phone.tap('#play');await phone.waitForFunction(()=>__rift.model.level.id===30&&!document.querySelector('#touch-controls').hidden);await phone.waitForFunction(()=>__rift.world.renderer.info.render.calls>0);console.log('Mobile island 30 render calls:',await phone.evaluate(()=>__rift.world.renderer.info.render.calls));
 await phone.evaluate(()=>{__rift.start(18);});await phone.waitForFunction(()=>__rift.world.linkGroup.children.length===2);assert.equal(await phone.evaluate(()=>__rift.world.linkGroup.children.length),2);console.log('PASS both linked-pair tethers are visible');
 await phone.evaluate(()=>__rift.start(30));for(const viewport of[{width:390,height:844},{width:360,height:640},{width:320,height:568},{width:667,height:375},{width:844,height:390}]){await phone.setViewportSize(viewport);await phone.waitForFunction(()=>{const a=document.querySelector('.level-info').getBoundingClientRect(),b=document.querySelector('#objective-status').getBoundingClientRect();return b.top>=a.bottom+4;});for(const selector of['#touch-stick','#touch-jump','#touch-grab','#pause-open','#record','#replay','#clear-echo']){const r=await phone.locator(selector).boundingBox();assert.ok(r&&r.x>=0&&r.y>=0&&r.x+r.width<=viewport.width+1&&r.y+r.height<=viewport.height+1,selector+' outside '+JSON.stringify(viewport));}await phone.tap('#pause-open');await phone.locator('#modal-buttons button').filter({hasText:'Карта острова'}).tap();const r=await phone.locator('#island-map').boundingBox();assert.ok(r&&r.x>=0&&r.x+r.width<=viewport.width+1);await phone.locator('#modal-buttons button').filter({hasText:'Вернуться в игру'}).tap();await phone.evaluate(()=>__rift.menu());for(let act=0;act<3;act++){await phone.locator('#act-tabs button').nth(act).tap();assert.equal(await phone.locator('.level-button:disabled').count(),0);}const menuButton=await phone.locator('#tutorial').boundingBox(),dock=await phone.locator('.level-dock').boundingBox();assert.ok(menuButton.y+menuButton.height<=dock.y+2,'menu buttons overlap the 30-level dock '+JSON.stringify({viewport,menuButton,dock}));assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth),viewport.width);await phone.tap('#play');}
 await phone.setViewportSize({width:390,height:844});await phone.evaluate(()=>{__rift.player.pos.set(7,0,-2);__rift.player.yaw=.1;});await phone.screenshot({path:'.artifacts/island-30-phone.png'});await phone.tap('#pause-open');await phone.locator('#modal-buttons button').filter({hasText:'Карта острова'}).tap();await phone.screenshot({path:'.artifacts/map-30-phone.png'});assert.deepEqual(errors,[]);console.log('PASS advanced island touch layouts, maps, menus and no exceptions');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
