const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/codex/cua_node/lib/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{let debugPage;const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const page=await context.newPage();debugPage=page;const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173/?qa',{waitUntil:'networkidle'});await page.tap('#play');assert.equal(await page.evaluate(()=>__rift.touch.enabled),true);assert.equal(await page.evaluate(()=>!!document.pointerLockElement),false);
const cdp=await context.newCDPSession(page);let points=new Map();
const emit=async type=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:[...points].map(([id,p])=>({id,x:p.x,y:p.y,radiusX:5,radiusY:5,force:1}))});
const down=async(id,x,y)=>{points.set(id,{x,y});await emit('touchStart');};const move=async(id,x,y)=>{points.set(id,{x,y});await emit('touchMove');};const up=async id=>{points.delete(id);await emit('touchEnd');};
const center=async selector=>{await page.locator(selector).waitFor({state:'visible'});const r=await page.locator(selector).boundingBox();assert.ok(r,selector);return{x:r.x+r.width/2,y:r.y+r.height/2,width:r.width,height:r.height};};
await page.evaluate(()=>{__rift.player.pos.set(0,0,6);__rift.player.yaw=0;});const stick=await center('#touch-stick');await down(1,stick.x,stick.y);await move(1,stick.x,stick.y-45);await page.waitForFunction(()=>__rift.player.pos.z<5.8);await down(2,250,410);const yaw=await page.evaluate(()=>__rift.player.yaw);await move(2,282,424);await page.waitForFunction(value=>__rift.player.yaw!==value,yaw);assert.notEqual(await page.evaluate(()=>__rift.player.yaw),yaw);assert.ok(await page.evaluate(()=>__rift.touch.movement.z<-.5));const jump=await center('#touch-jump');await down(3,jump.x,jump.y);await page.waitForFunction(()=>__rift.player.velY>0);await up(3);await up(2);await up(1);await page.waitForFunction(()=>__rift.touch.movement.z===0);console.log('PASS simultaneous joystick, camera swipe and jump');
const distance=await page.evaluate(()=>__rift.player.distance);await down(4,210,370);await down(5,300,370);await move(5,340,370);await page.waitForFunction(value=>__rift.player.distance<value,distance);assert.ok(await page.evaluate(()=>__rift.player.distance)<distance);await up(4);await up(5);console.log('PASS pinch zoom excludes control pointers');
await page.evaluate(()=>{__rift.start(1);__rift.player.pos.set(-2,0,3.3);__rift.player.yaw=0;});await page.waitForFunction(()=>!document.querySelector('#touch-grab').disabled);await page.tap('#touch-grab');assert.equal(await page.evaluate(()=>__rift.player.held),'m');await down(6,stick.x,stick.y);await move(6,stick.x,stick.y-45);await page.waitForFunction(()=>__rift.model.cubes[0].z<1);await up(6);await page.tap('#touch-grab');await page.waitForFunction(()=>!__rift.player.held);const changed=await page.evaluate(()=>__rift.model.cubes[0].z);await page.tap('#undo');assert.ok(await page.evaluate(()=>__rift.model.cubes[0].z)>changed);console.log('PASS touch grab, push, release and undo');
await page.tap('#restart');assert.equal(await page.evaluate(()=>__rift.state),'restart');await page.locator('#modal-buttons button').filter({hasText:'Продолжить игру'}).tap();assert.equal(await page.evaluate(()=>__rift.state),'playing');await page.tap('#hint-open');await page.tap('#hint-next');await page.tap('#hint-next');assert.equal(await page.locator('#hint-count').textContent(),'ПОДСКАЗКА 3 / 3');assert.ok(!(await page.locator('#hint-text').textContent()).includes('WASD'));await page.tap('#hint-close');await page.tap('#pause-open');await page.locator('#modal-buttons button').filter({hasText:'Настройки'}).tap();await page.selectOption('#quality','low');await page.locator('#modal-buttons button').filter({hasText:'Готово'}).tap();await page.locator('#modal-buttons button').filter({hasText:'Продолжить'}).tap();assert.equal(await page.evaluate(()=>__rift.world.renderer.shadowMap.enabled),false);console.log('PASS touch pause, settings, restart protection and hints');
await page.evaluate(()=>{__rift.start(4);__rift.player.pos.set(-2,0,5.3);__rift.player.yaw=0;});await page.waitForFunction(()=>!document.querySelector('#touch-grab').disabled);await page.tap('#touch-grab');await page.waitForFunction(()=>!document.querySelector('#touch-rotate').hidden);await page.tap('#touch-rotate');assert.equal(await page.evaluate(()=>__rift.model.cubes[0].rot),2);console.log('PASS reflector rotation without keyboard');
await page.evaluate(()=>{__rift.start(7);__rift.player.pos.set(-4,0,5.3);__rift.player.yaw=0;});await page.waitForFunction(()=>!document.querySelector('#touch-grab').disabled);await page.tap('#record');await page.tap('#touch-grab');await down(7,stick.x,stick.y);await move(7,stick.x,stick.y-45);await page.waitForFunction(()=>__rift.model.echo.events.length>0);await up(7);await page.tap('#record');assert.equal(await page.evaluate(()=>__rift.model.echo.recording),false);await page.tap('#replay');assert.equal(await page.evaluate(()=>__rift.model.echo.playing),true);await page.tap('#clear-echo');assert.equal(await page.evaluate(()=>__rift.model.echo.events.length),0);console.log('PASS touch echo recording, playback and reset');
await down(8,stick.x,stick.y);await move(8,stick.x-40,stick.y);points.clear();await emit('touchCancel');assert.equal(await page.evaluate(()=>__rift.touch.movement.x),0);await down(9,stick.x,stick.y);await move(9,stick.x-40,stick.y);await page.setViewportSize({width:844,height:390});assert.equal(await page.evaluate(()=>__rift.touch.movement.x),0);points.clear();await emit('touchCancel');console.log('PASS canceled touches and orientation change cannot leave movement stuck');
for(const viewport of [{width:844,height:390},{width:667,height:375},{width:390,height:844},{width:360,height:640},{width:320,height:568}]){await page.setViewportSize(viewport);await page.waitForFunction(()=>{const a=document.querySelector('.level-info').getBoundingClientRect(),b=document.querySelector('#objective-status').getBoundingClientRect();return b.top>=a.bottom+4;});for(const selector of ['#touch-stick','#touch-jump','#touch-grab','#pause-open','#record','#replay','#clear-echo']){const r=await page.locator(selector).boundingBox();assert.ok(r&&r.x>=-1&&r.y>=-1&&r.x+r.width<=viewport.width+1&&r.y+r.height<=viewport.height+1,`${selector} outside ${JSON.stringify(viewport)}: ${JSON.stringify(r)}`);if(selector!=='#touch-stick')assert.ok(r.width>=44&&r.height>=44,`${selector} too small`);}const info=await page.locator('.level-info').boundingBox(),status=await page.locator('#objective-status').boundingBox(),echo=await page.locator('#echo-panel').boundingBox();assert.ok(status.y>=info.y+info.height+4,'goal and status overlap '+JSON.stringify({viewport,info,status}));if(viewport.width>viewport.height)assert.ok(echo.x>=info.x+info.width+4,'echo overlaps landscape goal');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),viewport.width);}
await page.setViewportSize({width:390,height:844});await page.tap('#pause-open');await page.locator('#modal-buttons button').filter({hasText:'Выбор острова'}).tap();await page.tap('#tutorial');assert.equal(await page.evaluate(()=>__rift.model.level.id),0);await page.tap('#skip-tutorial');assert.equal(await page.evaluate(()=>__rift.model.level.id),1);assert.deepEqual(errors,[]);console.log('PASS small screens, landscape, touch tutorial and no browser exceptions');
}catch(e){console.error(e);if(debugPage)console.error(await debugPage.evaluate(()=>({state:window.__rift?.state,id:window.__rift?.model?.level.id,echo:window.__rift?.model?.echo,held:window.__rift?.player?.held,position:window.__rift?.player?.pos.toArray(),touch:window.__rift?.touch?.movement})).catch(()=>null));process.exitCode=1;}finally{await browser.close();}
})();
