import './style.css';
import * as THREE from 'three';
import {levels,tutorial,TYPES} from './levels.js';
import {Puzzle} from './model.js';
import {World} from './world.js';
import {Player} from './player.js';
import {Sound} from './audio.js';
import {TouchControls} from './touch.js';
const $=s=>document.querySelector(s), pad=n=>String(n).padStart(2,'0');
const STORAGE='rift-cubes-v1';
const defaults={unlocked:1,completed:[],current:1,volume:.35,sensitivity:1,quality:'auto'};
let saved={...defaults};try{const d=JSON.parse(localStorage.getItem(STORAGE)||'null');if(d&&typeof d==='object')saved={...defaults,...d,unlocked:Math.max(1,Math.min(10,Number(d.unlocked)||1)),current:Math.max(1,Math.min(10,Number(d.current)||1)),completed:Array.isArray(d.completed)?d.completed.filter(n=>Number.isInteger(n)&&n>=1&&n<=10):[],volume:Math.max(0,Math.min(1,Number(d.volume) || 0)),sensitivity:Math.max(.3,Math.min(2.5,Number(d.sensitivity)||1))};}catch{}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(saved));}catch{toast('Браузер не разрешает сохранение. Прогресс доступен до закрытия вкладки.');}}
let touch,world,model,player,state='menu',level=levels[0],keys=new Set(),hintStep=-1,elapsed=0,moves=0,readyBefore=false,toastTimer,introTimer,ignoreUnlock=false,settingsReturn='menu',finishTimer=0;
const sound=new Sound(saved.volume);
if(!['auto','high','low'].includes(saved.quality))saved.quality='auto';
function uiText(text){if(!touch?.enabled)return text;return text.replace(/WASD/g,'джойстик').replace(/Пробел/g,'«Прыжок»').replace(/пробелом/g,'кнопкой «Прыжок»').replace(/\bE\b/g,'«Взять / отпустить»').replace(/\bQ\b/g,'«Поворот»').replace(/\bV\b/g,'«Запись»').replace(/\bB\b/g,'«Повтор»').replace(/\bC\b/g,'«Сброс»');}
function action(name){if(state!=='playing')return;sound.start();switch(name){case 'jump':player.queueJump();break;case 'grab':player.grab();sound.note(440,.12,.3);break;case 'rotate':if(player.held&&model.rotate(player.held)){moves++;sound.move();}break;}}
function requestRestart(){if(!touch.enabled){start(level);return;}state='restart';modal({kicker:'НАЧАТЬ С ЧИСТОГО ЛИСТА',title:'Сбросить остров?',description:'Позиции кубов и запись эхо сбросятся. Открытые острова сохранятся.',buttons:[{label:'Продолжить игру',action:resume},{label:'Начать заново',action:()=>start(level)}]});}
async function fullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch{toast('Полный экран недоступен в этом браузере.');}}
touch=new TouchControls({canvas:$('#game'),stick:$('#touch-stick'),knob:$('#stick-knob'),active:()=>state==='playing',onLook:(x,y)=>{player.yaw-=x*.004*saved.sensitivity;player.pitch=THREE.MathUtils.clamp(player.pitch+y*.0035*saved.sensitivity,.14,1.22);},onZoom:amount=>{player.distance=THREE.MathUtils.clamp(player.distance+amount,4.5,17);},onAction:action,onMode:()=>{world?.setQuality(saved.quality,true);$('.desktop-note').textContent='Джойстик слева · обзор свайпом справа';},onReset:()=>{keys.clear();if(player)player.jumpQueued=false;}});
if(touch.enabled)$('.desktop-note').textContent='Джойстик слева · обзор свайпом справа';
new ResizeObserver(()=>{const bottom=$('.level-info').getBoundingClientRect().bottom;document.body.style.setProperty('--info-bottom',bottom+'px');}).observe($('.level-info'));

function toast(message){$('#toast').textContent=uiText(message);$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function releasePointer(){ignoreUnlock=true;if(document.pointerLockElement)document.exitPointerLock();setTimeout(()=>ignoreUnlock=false,150);keys.clear();touch?.reset();}
function capture(){if(touch.enabled){$('#capture-tip').hidden=true;sound.start();return;}try{const p=$('#game').requestPointerLock?.();if(p?.catch)p.catch(()=>{$('#capture-tip').hidden=false;});}catch{$('#capture-tip').hidden=false;}sound.start();}
function buildMenu(){const container=$('#levels');container.replaceChildren();for(const l of levels){const b=document.createElement('button');b.className='level-button'+(l.id===saved.current?' current':'')+(saved.completed.includes(l.id)?' completed':'');b.disabled=l.id>saved.unlocked;b.innerHTML=`<strong>${pad(l.id)}</strong><small>${l.name}</small>${b.disabled?'<span class="lock">▧</span>':''}`;b.title=b.disabled?`${l.name} — пройдите предыдущий остров`:l.name;b.setAttribute('aria-label',`Уровень ${l.id}: ${l.name}${b.disabled?', закрыт':''}`);b.addEventListener('click',()=>start(l));container.append(b);}$('#progress-label').textContent=`Открыто островов: ${saved.unlocked} из 10`;$('#continue-number').textContent=`${pad(saved.current)} / 10`;$('#play-label').textContent=saved.completed.length?'Продолжить':'Играть';}
function load(l){keys.clear();touch.reset();level=l;model=new Puzzle(l);world.build(model);player=new Player(model,world);player.distance=touch.enabled?11.5:10;model.canReplay=(c,x,z)=>{const y=model.height(x,z);return player.pos.y>=y+1.46||!player.overlap(player.pos.x,player.pos.z,{x:x*2,z:z*2,w:.75,d:.75});};player.onMessage=toast;player.onMove=()=>{moves++;sound.move();};player.onJump=()=>sound.note(392,.18,.2);elapsed=0;moves=0;hintStep=-1;readyBefore=false;finishTimer=0;$('#hint-panel').hidden=true;$('#interaction').hidden=true;$('#mechanic-card').hidden=true;$('#toast').classList.remove('show');$('#chapter').textContent=l.id?`ОСТРОВ ${pad(l.id)} / 10 · ${l.chapter}`:l.chapter;$('#level-name').textContent=l.name;$('#goal').textContent=l.goal;$('#echo-panel').hidden=!l.cubes.some(c=>c.type==='echo');$('#skip-tutorial').hidden=!!l.id;$('#hint-open').hidden=!l.id;$('#journey').innerHTML=levels.map(k=>`<i class="${k.id<l.id?'done':k.id===l.id?'active':''}" title="${k.name}"></i>`).join('');}
function start(l){$('#modal').hidden=true;document.body.classList.remove('ending');state='playing';load(l);if(l.id){saved.current=l.id;save();}document.body.classList.add('playing');$('#menu').hidden=true;$('#hud').hidden=false;const intro=$('#level-intro');intro.querySelector('small').textContent=l.id?`ОСТРОВ ${pad(l.id)}`:'ПЕРВЫЕ 30 СЕКУНД';intro.querySelector('h2').textContent=l.name;intro.querySelector('p').textContent=touch.enabled&&l.id===0?'Двигайтесь джойстиком. Подойдите к кубу и нажмите «Взять».':uiText(l.intro);intro.classList.add('show');clearTimeout(introTimer);introTimer=setTimeout(()=>intro.classList.remove('show'),3300);player.camera(1);capture();}
function menu(){releasePointer();state='menu';$('#modal').hidden=true;$('#menu').hidden=false;$('#hud').hidden=true;document.body.classList.remove('playing','ending');load(levels[0]);world.camera.position.set(16,16,23);buildMenu();}
function modal({kicker,title,description='',content='',buttons=[]}){releasePointer();$('#modal').hidden=false;$('#modal-kicker').textContent=kicker;$('#modal-title').textContent=title;$('#modal-description').textContent=description;$('#modal-content').innerHTML=content;const b=$('#modal-buttons');b.replaceChildren();buttons.forEach((o,i)=>{const el=document.createElement('button');el.className=i===0?'primary':'secondary';el.textContent=o.label;el.onclick=o.action;b.append(el);});}
function pause(){if(state!=='playing')return;state='paused';modal({kicker:'МОЖНО НЕ ТОРОПИТЬСЯ',title:'Мир подождёт',description:`Остров ${pad(level.id)} · ${level.name}`,buttons:[{label:'Продолжить',action:resume},{label:'Начать остров заново',action:()=>start(level)},{label:'Настройки',action:settings},...(touch.enabled&&document.fullscreenEnabled?[{label:document.fullscreenElement?'Выйти из полного экрана':'На весь экран',action:fullscreen}]:[]),{label:'Выбор острова',action:menu}]});}
function resume(){state='playing';$('#modal').hidden=true;capture();}
function settings(){settingsReturn=state;state='settings';const help=touch.enabled?'Джойстик слева — движение. Свайп по острову — обзор.<br>«Взять» — захватить или отпустить куб. «Прыжок» — прыгнуть.<br>Два пальца на острове — приблизить или отдалить камеру.<br>Для отражателя появляется кнопка «Поворот». Для эхо — «Запись», «Повтор», «Сброс».<br>Играть можно вертикально и горизонтально.':'WASD — движение · Мышь — обзор<br>Пробел — прыжок · E — захватить / отпустить<br>Q — повернуть отражатель · Колесо — масштаб<br>V / B / C — запись / повтор / сброс эхо<br>Z — отмена · R — заново · H — подсказка<br>Esc — пауза и свободный курсор';modal({kicker:'ВАШ РИТМ',title:'Настройки',content:`<label class="setting"><span>Громкость <output id="volume-value">${Math.round(saved.volume*100)}%</output></span><input id="volume" aria-label="Громкость" type="range" min="0" max="1" step=".01" value="${saved.volume}"></label><label class="setting"><span>Чувствительность камеры <output id="sensitivity-value">${saved.sensitivity.toFixed(1)}×</output></span><input id="sensitivity" aria-label="Чувствительность камеры" type="range" min=".3" max="2.5" step=".1" value="${saved.sensitivity}"></label><label class="setting"><span>Графика</span><select id="quality" aria-label="Качество графики"><option value="auto">Авто — под устройство</option><option value="high">Высокое качество</option><option value="low">Экономно — меньше нагрев</option></select></label><p class="settings-help">${help}</p>`,buttons:[{label:'Готово',action:()=>{save();$('#modal').hidden=true;state=settingsReturn;if(state==='playing')capture();if(state==='paused'){state='playing';pause();}}}]});$('#quality').value=saved.quality;$('#quality').onchange=e=>{saved.quality=e.target.value;world.setQuality(saved.quality,touch.enabled);save();};$('#volume').oninput=e=>{saved.volume=+e.target.value;sound.setVolume(saved.volume);$('#volume-value').textContent=Math.round(saved.volume*100)+'%';sound.start();};$('#sensitivity').oninput=e=>{saved.sensitivity=+e.target.value;$('#sensitivity-value').textContent=saved.sensitivity.toFixed(1)+'×';};}
function complete(){if(state!=='playing')return;player.release();releasePointer();sound.success();state='complete';if(level.id){saved.completed=[...new Set([...saved.completed,level.id])];saved.unlocked=Math.min(10,Math.max(saved.unlocked,level.id+1));saved.current=Math.min(10,level.id+1);save();}const final=level.id===10;if(final){world.celebrate();document.body.classList.add('ending');finishTimer=world.time;}
 const minutes=Math.floor(elapsed/60),seconds=Math.floor(elapsed%60);modal({kicker:final?'ОБСЕРВАТОРИЯ СНОВА ЖИВА':level.id?'ЕЩЁ ОДИН ОСТРОВ ПРОСНУЛСЯ':'ВЫ ГОТОВЫ К ПУТЕШЕСТВИЮ',title:final?'Свет вернулся.':level.id?'Разлом восстановлен':'Первый шаг сделан',description:final?'Десять островов снова связаны. В древних механизмах звучит жизнь, а у маленького робота теперь есть дом.':level.id?`${level.name}. Энергия снова течёт сквозь камень.`:'Вы умеете двигаться, перемещать кубы и открывать порталы.',content:`${final?'<div class="complete-emblem">✧ ◇ ✧</div>':''}<div class="level-stats"><div><strong>${minutes}:${pad(seconds)}</strong><span>ВРЕМЯ НА ОСТРОВЕ</span></div><div><strong>${moves}</strong><span>ПЕРЕМЕЩЕНИЙ</span></div></div>`,buttons:[{label:final?'Вернуться к островам':level.id?'Следующий остров':'Начать приключение',action:()=>final?menu():start(level.id?levels[level.id]:levels[0])},...(!final?[{label:'Выбор острова',action:menu}]:[{label:'Снова посетить обсерваторию',action:()=>start(levels[9])}])]});}
function undo(){if(state!=='playing')return;player.release();if(model.undo()){toast('Последнее действие отменено.');sound.note(261,.2,.4);recoverPlayer();}else toast('Пока нечего отменять.');}
function recoverPlayer(){if(player.blocked(player.pos.x,player.pos.y,player.pos.z,player.solids())){player.pos.copy(player.safe);if(player.blocked(player.pos.x,player.pos.y,player.pos.z,player.solids()))player.pos.set(level.spawn[0]*2,model.height(...level.spawn),level.spawn[1]*2);player.velY=0;}}
function echo(action){if(state!=='playing')return;if(action==='record'){if(model.toggleRecord()){sound.note(model.echo.recording?523:392,.2,.5);toast(model.echo.recording?'Запись началась. Двигайте куб; V завершает запись.':'Маршрут записан. B — запустить повтор.');}}else if(action==='play'){player.release();if(model.play()){recoverPlayer();toast('Эхо повторяет маршрут. В конце — пауза 5 секунд.');sound.note(659,.4,.5);}else toast('Сначала запишите маршрут: V, движения куба, V.');}else{player.release();model.resetEcho();recoverPlayer();toast('Запись очищена. Можно записать новый путь.');}}
function showHint(){if(state!=='playing'&&state!=='hint')return;state='hint';releasePointer();hintStep=Math.min(2,hintStep+1);$('#hint-panel').hidden=false;$('#hint-count').textContent=`ПОДСКАЗКА ${hintStep+1} / 3`;$('#hint-text').textContent=uiText(level.hints[hintStep]);$('#hint-next').hidden=hintStep===2;}
function closeHint(){if(state==='hint'){state='playing';$('#hint-panel').hidden=true;capture();}}
function updateHud(){const near=player.held?model.cubes.find(c=>c.id===player.held):player.nearest();$('#interaction').hidden=!near;$('#mechanic-card').hidden=!near;if(near){const type=TYPES[near.type];$('#interaction').innerHTML=touch.enabled?`<span>${type.name}<small>Клетка (${near.x}, ${near.z}) · ${player.held?'в захвате':'рядом'}</small></span>`:`<kbd>E</kbd><span>${player.held?'Отпустить': 'Захватить'} · ${type.name}</span>${player.held&&near.type==='reflector'?'<small>Q — поворот</small>':''}`;$('#mechanic-card').innerHTML=`<strong>${type.symbol} &nbsp; ${type.name}</strong><p>${uiText(type.help)}</p><p class="cube-position">Клетка (${near.x}, ${near.z})</p>`;}
 const labels={a:'Плита I',b:'Плита II',p:'Ворота',power:'Энергия',phase:'Фаза',light:'Приёмник',memory:'Путь эхо',sync:'Синхронизация',sector1:'I · Энергия',sector2:'II · Оптика'};let needs=level.requires;let chips=needs.map(k=>`<span class="objective-chip ${model.flags[k]?'on':''}">${model.flags[k]?'✓':'◇'} ${labels[k]||'Механизм'}</span>`).join('');if(level.echoRule)chips+=`<span class="objective-chip ${model.pulses.a>0?'on':''}">I · ${model.pulses.a.toFixed(1)} с</span><span class="objective-chip ${model.pulses.b>0?'on':''}">II · ${model.pulses.b.toFixed(1)} с</span>`;if(level.syncRule)chips+=`<span class="objective-chip">${model.latched.sync?'✓':model.sync.toFixed(1)+' / 3.0 с'} · ${['a','b','beat'].map(k=>model.flags[k]?'●':'○').join(' ')}</span>`;$('#objective-status').innerHTML=chips;
 if(!$('#echo-panel').hidden){const e=model.echo;$('#record').classList.toggle('active',e.recording);$('#replay').classList.toggle('active',e.playing);$('#record').innerHTML=`<kbd>V</kbd> ${e.recording?'Стоп':'Запись'}`;$('#echo-time').textContent=e.recording?`${e.time.toFixed(1)} / 12 с`:e.playing?`${e.playTime.toFixed(1)} / ${(e.duration+5).toFixed(1)} с`:`${e.events.length} шагов`;$('#echo-progress').style.width=(e.recording?e.time/12:e.playing?e.playTime/(e.duration+5):0)*100+'%';$('#echo-tip').textContent=e.blocked?'Путь занят. Освободите его или нажмите C.':e.recording?'Двигайте куб. V — завершить запись.':e.playing?e.playTime>e.duration?'Пауза в конце пути · следующий цикл автоматически':'Эхо повторяет путь · B — начать цикл заново':e.events.length?'Маршрут готов. B — повторить по кругу.':'V — запись, затем перемещайте куб.';}
 $('#undo').disabled=!model.history.length;$('#capture-tip').hidden=touch.enabled||!!document.pointerLockElement||state!=='playing';
 $('#touch-grab-label').textContent=player.held?'Отпустить':'Взять';$('#touch-grab').setAttribute('aria-label',player.held?'Отпустить куб':'Взять куб');$('#touch-grab').disabled=!near;$('#touch-grab').classList.toggle('holding',!!player.held);$('#touch-jump').disabled=!!player.held;$('#touch-rotate').hidden=!(player.held&&near?.type==='reflector');
 if(touch.enabled)$('#echo-tip').textContent=uiText($('#echo-tip').textContent);return near;}
$('#play').onclick=()=>start(levels[Math.min(saved.current,saved.unlocked)-1]);$('#tutorial').onclick=()=>start(tutorial);$('#settings-open').onclick=settings;$('#sound-toggle').onclick=()=>{sound.start();$('#sound-toggle').textContent=sound.toggle()?'♩':'♪';$('#sound-toggle').title=sound.muted?'Включить звук':'Выключить звук';};$('#pause-open').onclick=pause;$('#restart').onclick=requestRestart;$('#undo').onclick=undo;$('#skip-tutorial').onclick=()=>start(levels[0]);$('#hint-open').onclick=showHint;$('#hint-next').onclick=showHint;$('#hint-close').onclick=closeHint;$('#record').onclick=()=>echo('record');$('#replay').onclick=()=>echo('play');$('#clear-echo').onclick=()=>echo('clear');$('#game').onclick=()=>{if(state==='playing')capture();};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;const handled=['Space','KeyW','KeyA','KeyS','KeyD','KeyE','KeyQ','KeyR','KeyZ','KeyV','KeyB','KeyC','KeyH'];if(handled.includes(e.code)&&state==='playing')e.preventDefault();if(e.code==='Escape'){if(state==='hint')closeHint();else if(state==='playing')pause();else if(state==='paused')resume();return;}if(state!=='playing')return;keys.add(e.code);if(e.repeat)return;switch(e.code){case'Space':action('jump');break;case'KeyE':action('grab');break;case'KeyQ':action('rotate');break;case'KeyR':start(level);break;case'KeyZ':undo();break;case'KeyV':echo('record');break;case'KeyB':echo('play');break;case'KeyC':echo('clear');break;case'KeyH':showHint();break;}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){sound.ctx?.suspend();if(state==='playing')pause();}});
window.addEventListener('pagehide',()=>{if(state==='playing')pause();});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&!ignoreUnlock&&state==='playing')pause();});let draggingCamera=false;$('#game').addEventListener('mousedown',e=>{if(e.button===2)draggingCamera=true;});window.addEventListener('mouseup',()=>draggingCamera=false);$('#game').addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('mousemove',e=>{if(touch.enabled||state!=='playing'||(!document.pointerLockElement&&!draggingCamera))return;player.yaw-=e.movementX*.0024*saved.sensitivity;player.pitch=THREE.MathUtils.clamp(player.pitch+e.movementY*.002*saved.sensitivity,.14,1.22);});$('#game').addEventListener('wheel',e=>{if(state==='playing'){e.preventDefault();player.distance=THREE.MathUtils.clamp(player.distance+e.deltaY*.008,4.5,17);}}, {passive:false});
let previous=performance.now(),hudAccumulator=0,lastNear;
function frame(now){requestAnimationFrame(frame);const rawDt=(now-previous)/1000,dt=Math.min(.04,rawDt);previous=now;if(!world)return;const active=state==='playing';world.noteFrame(rawDt,active);$('#touch-controls').hidden=!touch.enabled||!active;$('#touch-coach').hidden=elapsed>9||![0,1].includes(level.id);if(active){elapsed+=dt;model.tick(dt);player.update(dt,keys,touch.movement);const lost=model.cubes.filter(c=>!model.floor(c.x,c.z));if(lost.length){player.release();for(const c of lost){const originals=c.pair?model.initial.filter(i=>i.id===c.id||i.id===c.pair):model.initial.filter(i=>i.id===c.id);for(const o of originals)Object.assign(model.cubes.find(b=>b.id===o.id),o);}model.evaluate();toast('Куб вернулся на устойчивую площадку.');}
 if(model.ready&&!readyBefore){toast('Портал открыт. Остров ждёт вас.');sound.success();}readyBefore=model.ready;const [x,z]=level.portal;if(model.ready&&Math.hypot(player.pos.x-x*2,player.pos.z-z*2)<1.05&&Math.abs(player.pos.y-model.height(x,z))<1.4)complete();}
 hudAccumulator+=dt;if((active||state==='hint')&&hudAccumulator>.09){lastNear=updateHud();hudAccumulator=0;}
 world.update(active?dt:Math.min(dt,.02),player,player.held,lastNear?.id,state==='menu',level.id===10&&state==='complete');
 if(state==='menu'||state==='settings'&&settingsReturn==='menu'){const t=world.time;world.robot.position.set(1.3,.02,4.1);world.robot.rotation.y=-.5;world.camera.position.lerp(new THREE.Vector3(16+Math.sin(t*.05)*.4,16,23),.035);world.camera.lookAt(-4.7,.1,-1.7);}else if(state==='complete'&&level.id===10){const t=(world.time-finishTimer)*.13;world.camera.position.lerp(new THREE.Vector3(Math.sin(t)*17,14,level.portal[1]*2+Math.cos(t)*17),dt*.5);world.camera.lookAt(0,1,level.portal[1]*2+4);}else player.camera(dt);
 world.render();}
try{world=new World($('#game'),{mobile:touch.enabled,quality:saved.quality});load(levels[0]);buildMenu();$('#loading').hidden=true;requestAnimationFrame(frame);}catch(error){console.error(error);$('#loading').innerHTML='<p>Не удалось включить 3D-графику.</p><p>Откройте игру в Chrome, Edge или Firefox с включённым WebGL.</p><button onclick="location.reload()" class="primary">Попробовать снова</button>';}
// Read-only QA snapshot plus deterministic hooks only in an explicit local test session.
if(import.meta.env.DEV&&new URLSearchParams(location.search).has('qa'))window.__rift={get state(){return state;},get model(){return model;},get player(){return player;},get world(){return world;},get touch(){return touch;},start:id=>start(id===0?tutorial:levels[id-1]),menu,complete,save,get saved(){return saved;},get elapsed(){return elapsed;}};
