import * as THREE from 'three';
import {TYPES} from './levels.js';
import {CELL,CUBE_SIZE} from './model.js';
const TAU=Math.PI*2;
const mats=new Map();
export function material(color,extra={}){const k=color+JSON.stringify(extra);if(!mats.has(k))mats.set(k,new THREE.MeshStandardMaterial({color,roughness:.78,...extra}));return mats.get(k);}
export function box(w,h,d,color,extra={}){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color,extra));m.castShadow=true;m.receiveShadow=true;return m;}
function bevel(w,h,d,color,r=.08,extra={}){const shape=new THREE.Shape(),x=-w/2,y=-h/2;shape.moveTo(x+r,y);shape.lineTo(x+w-r,y);shape.quadraticCurveTo(x+w,y,x+w,y+r);shape.lineTo(x+w,y+h-r);shape.quadraticCurveTo(x+w,y+h,x+w-r,y+h);shape.lineTo(x+r,y+h);shape.quadraticCurveTo(x,y+h,x,y+h-r);shape.lineTo(x,y+r);shape.quadraticCurveTo(x,y,x+r,y);const g=new THREE.ExtrudeGeometry(shape,{depth:d-2*r,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:r,bevelThickness:r,curveSegments:3});g.translate(0,0,-d/2+r);const m=new THREE.Mesh(g,material(color,extra));m.castShadow=true;m.receiveShadow=true;return m;}
function at(obj,x,y,z,parent){obj.position.set(x,y,z);parent.add(obj);return obj;}
function cyl(radius,height,color,n=12){const m=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,height,n),material(color));m.castShadow=true;m.receiveShadow=true;return m;}
function ring(radius,tube,color){return new THREE.Mesh(new THREE.TorusGeometry(radius,tube,6,48),material(color,{emissive:color,emissiveIntensity:.35}));}
function glow(color){return material(color,{emissive:color,emissiveIntensity:1.3,roughness:.35});}
function line(points,color,width=.035){const group=new THREE.Group();for(let i=1;i<points.length;i++){const a=new THREE.Vector3(...points[i-1]),b=new THREE.Vector3(...points[i]),dir=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(width,width,dir.length(),6),glow(color));m.position.copy(a.add(b).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.normalize());group.add(m);}return group;}
export function makeRobot(){const g=new THREE.Group(),body=new THREE.Group();g.add(body);at(bevel(.62,.6,.44,0xe4e9dd),0,.71,0,body);at(bevel(.8,.5,.56,0xf3f0df),0,1.22,0,body);at(bevel(.61,.29,.035,0x183f48,.035),0,1.23,-.304,body);for(const x of [-.15,.15])at(bevel(.085,.11,.025,0x75f4df,.02,{emissive:0x75f4df,emissiveIntensity:1.5}),x,1.25,-.335,body);at(box(.22,.13,.025,0xea9950),0,.76,-.239,body);at(box(.14,.22,.16,0x476771),0,.98,.26,body);for(const x of [-.46,.46]){const e=cyl(.14,.12,0xe8944f);e.rotation.z=Math.PI/2;at(e,x,1.22,0,body);}at(cyl(.025,.22,0x496670),.2,1.57,0,body);at(new THREE.Mesh(new THREE.IcosahedronGeometry(.07,1),glow(0xf7b35f)),.2,1.71,0,body);
 const limbs=[];for(const side of [-1,1]){const leg=new THREE.Group();at(leg,side*.2,.4,0,g);at(bevel(.22,.29,.24,0x668088,.04),0,-.08,0,leg);at(bevel(.29,.16,.42,0xe7e7d9,.045),0,-.3,-.055,leg);limbs.push(leg);const arm=new THREE.Group();at(arm,side*.44,.93,0,body);at(bevel(.18,.41,.2,0xe6e8da,.045),0,-.17,0,arm);at(box(.19,.12,.2,0xe8964e),0,-.37,0,arm);limbs.push(arm);}g.userData={body,limbs};return g;}
export function makeCube(type){const g=new THREE.Group(),col=TYPES[type].color;const core=bevel(1.2,1.2,1.2,type==='mass'?0xbd946d:0x466b74,.085);at(core,0,.73,0,g);for(const x of [-.6,.6])for(const y of [.15,1.31])for(const z of [-.6,.6])at(bevel(.29,.29,.29,0xe2dfca,.045),x,y,z,g);
 for(let i=0;i<4;i++){const side=new THREE.Group();side.rotation.y=i*Math.PI/2;g.add(side);at(bevel(.72,.72,.05,0x234750,.045),0,.73,-.663,side);const sym=new THREE.Group();at(sym,0,.73,-.706,side);
 if(type==='mass'){const p=box(.37,.37,.055,col);sym.add(p);at(box(.19,.19,.065,0x3d5153),0,0,-.04,sym);}
 if(type==='conductor'){const pts=[[-.04,.3,-.01],[-.2,-.03,-.01],[.18,.03,-.01],[.03,-.29,-.01]];sym.add(line(pts,col,.045));}
 if(type==='reflector'){const p=box(.37,.37,.04,col,{metalness:.55,roughness:.2,emissive:col,emissiveIntensity:.2});p.rotation.z=Math.PI/4;sym.add(p);}
 if(type==='linked'){for(const x of [-.11,.11]){const r=ring(.14,.027,col);at(r,x,0,0,sym);}}
 if(type==='echo'){const r=ring(.25,.03,col);sym.add(r);sym.add(line([[0,.18,0],[0,0,0],[.13,-.09,0]],col,.025));}}
 const top=ring(.37,.03,col);top.rotation.x=-Math.PI/2;at(top,0,1.45,0,g);
 if(type==='reflector'){const mirror=box(1.1,.07,.13,0xbbe6eb,{metalness:.8,roughness:.1});mirror.rotation.y=-Math.PI/4;at(mirror,0,1.46,0,g);}
 if(type==='conductor')for(const x of [-.7,.7])at(box(.12,.5,.34,col,{emissive:col,emissiveIntensity:.45}),x,.73,0,g);
 const selection=new THREE.Mesh(new THREE.BoxGeometry(1.66,1.6,1.66),new THREE.MeshBasicMaterial({color:0xe5fff0,wireframe:true,transparent:true,opacity:.72}));selection.position.y=.74;selection.visible=false;g.add(selection);g.userData={selection,core};return g;}
function makeTree(x,y,z,scale,parent){const g=new THREE.Group();at(g,x,y,z,parent);g.scale.setScalar(scale);const trunk=cyl(.11,1.5,0x766e53,5);trunk.rotation.z=.15;at(trunk,0,.7,0,g);for(let i=0;i<4;i++){const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.85-i*.1,0),material([0x538d73,0x79ad81,0x92b684,0x649c75][i]));at(crown,Math.sin(i*2)*.43,1.25+i*.28,Math.cos(i*2)*.4,g);crown.castShadow=true;}return g;}
function rng(seed){return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
export class World{
 constructor(canvas,{mobile=false,quality='auto'}={}){this.mobile=mobile;this.quality=quality;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;
 this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0xa8c9c8);this.scene.fog=new THREE.FogExp2(0xa8c9c8,.009);this.camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.12,250);this.scene.add(new THREE.HemisphereLight(0xdcf9ff,0x638075,2.3));const sun=new THREE.DirectionalLight(0xffe5b6,3.2);sun.position.set(-18,30,16);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-24;sun.shadow.camera.right=24;sun.shadow.camera.top=24;sun.shadow.camera.bottom=-34;sun.shadow.camera.far=100;sun.shadow.normalBias=.035;sun.shadow.bias=-.0003;this.scene.add(sun);this.sun=sun;this.scene.add(sun.target);
 this.backdrop=new THREE.Group();this.scene.add(this.backdrop);this.makeBackdrop();this.group=new THREE.Group();this.scene.add(this.group);this.robot=makeRobot();this.scene.add(this.robot);this.rayGroup=new THREE.Group();this.scene.add(this.rayGroup);this.linkGroup=new THREE.Group();this.scene.add(this.linkGroup);this.particles=this.makeParticles();this.time=0;this.camera.position.set(16,16,23);this.camera.lookAt(-4.7,.1,-1.7);this.setQuality(quality,mobile);this.resize();window.addEventListener('resize',()=>this.resize());window.visualViewport?.addEventListener('resize',()=>this.resize());}
 resize(){const r=this.renderer.domElement.getBoundingClientRect(),w=Math.max(1,Math.round(r.width)),h=Math.max(1,Math.round(r.height));this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 setQuality(quality=this.quality,mobile=this.mobile){this.quality=quality;this.mobile=mobile;this.adapted=false;this.frameSamples=[];const low=quality==='low',size=low?512:mobile?1024:2048;this.renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:mobile?(quality==='high'?1.5:1.15):1.75));this.renderer.shadowMap.enabled=!low;if(this.sun.shadow.mapSize.x!==size){this.sun.shadow.map?.dispose();this.sun.shadow.map=null;this.sun.shadow.mapSize.set(size,size);}this.resize();}
 noteFrame(dt,active){if(!active||!this.mobile||this.quality!=='auto'||this.adapted||dt>.5)return;this.frameSamples.push(dt);if(this.frameSamples.length<90)return;const average=this.frameSamples.reduce((a,b)=>a+b,0)/this.frameSamples.length;this.frameSamples=[];if(average>.043){this.adapted=true;this.renderer.setPixelRatio(Math.min(devicePixelRatio,.9));this.renderer.shadowMap.enabled=false;this.resize();}}
 batchFloors(){const batches=new Map();for(const {t,m} of this.tileMeshes){if(t.bridge)continue;const list=batches.get(m.material)||[];list.push(m);batches.set(m.material,list);}for(const [mat,list] of batches){const mesh=new THREE.InstancedMesh(new THREE.BoxGeometry(1.98,.58,1.98),mat,list.length);mesh.castShadow=true;mesh.receiveShadow=true;list.forEach((m,i)=>{m.updateMatrix();mesh.setMatrixAt(i,m.matrix);this.group.remove(m);m.geometry.dispose();});mesh.computeBoundingSphere();this.group.add(mesh);}this.tileMeshes=this.tileMeshes.filter(o=>o.t.bridge);}

 makeBackdrop(){const random=rng(89);this.clouds=[];for(let i=0;i<32;i++){const g=new THREE.Group();for(let j=0;j<4;j++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(3+random()*3,1),material(0xe4e9dc,{transparent:true,opacity:.32,flatShading:true,depthWrite:false}));at(m,j*3-5,random(),random()*2,g);m.scale.y=.34;}at(g,(random()-.5)*160,-9-random()*13,(random()-.5)*140,this.backdrop);this.clouds.push(g);}
 for(let i=0;i<13;i++){const x=(i%2===0?-1:1)*(23+random()*48),z=-15-random()*90,y=-5+random()*13;const g=new THREE.Group();at(g,x,y,z,this.backdrop);const rock=new THREE.Mesh(new THREE.ConeGeometry(4+random()*5,8+random()*6,5),material(0x658b87,{flatShading:true}));rock.rotation.z=Math.PI;at(rock,0,-4,0,g);const top=cyl(4.2,.5,0x9baf92,6);at(top,0,0,0,g);for(let j=0;j<3;j++)makeTree((random()-.5)*4,.3,(random()-.5)*4,.9+random(),g);const column=cyl(.5,4,0xc5c8b1,8);at(column,2,2,0,g);}}
 makeParticles(){const points=new Float32Array(210*3),random=rng(44);for(let i=0;i<210;i++){points[i*3]=(random()-.5)*70;points[i*3+1]=random()*18-3;points[i*3+2]=(random()-.5)*65;}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(points,3));const p=new THREE.Points(geo,new THREE.PointsMaterial({color:0xf5e9be,size:.05,transparent:true,opacity:.6}));this.scene.add(p);return p;}
 clearGroup(g){for(const o of [...g.children]){g.remove(o);o.traverse(p=>{if(p.geometry)p.geometry.dispose();if(p.material&&!([...mats.values()].includes(p.material))){if(Array.isArray(p.material))p.material.forEach(m=>m.dispose());else p.material.dispose();}});}}
 build(model){this.clearGroup(this.group);this.clearGroup(this.rayGroup);this.clearGroup(this.linkGroup);this.model=model;model.decorations=[];this.celebration=null;this.sun.color.set(0xffe5b6);this.tileMeshes=[];this.wallMeshes=[];this.cubeMeshes=new Map();this.plateMeshes=[];this.nodeMeshes=[];this.gateMeshes=[];this.liftMeshes=[];this.rayKey='';this.linkKey='';const l=model.level,random=rng(321+l.id);const occupied=new Set([...(l.walls||[]),...(l.plates||[]),...l.cubes,...(l.contacts||[]),...(l.sources||[]),...(l.receivers||[]),...(l.lasers||[]),{x:l.portal[0],z:l.portal[1]}].map(o=>`${o.x},${o.z}`));
 for(const t of l.floors){const col=t.bridge?0x66b5af:[0xcacabb,0xd3d0bf,0xc3c8b7,0xd7d2be][Math.floor(random()*4)];const m=box(1.98,.58,1.98,col);at(m,t.x*2,t.y-.31,t.z*2,this.group);this.tileMeshes.push({t,m});const border=!l.floors.some(a=>a.x===t.x+1&&a.z===t.z)||!l.floors.some(a=>a.x===t.x-1&&a.z===t.z)||!l.floors.some(a=>a.x===t.x&&a.z===t.z+1)||!l.floors.some(a=>a.x===t.x&&a.z===t.z-1);
 if(border&&!t.bridge){const stone=new THREE.Mesh(new THREE.IcosahedronGeometry(1.55+random()*.4,0),material([0x667e76,0x849585,0x9aa48f][Math.floor(random()*3)],{flatShading:true}));at(stone,t.x*2,t.y-3.6,t.z*2,this.group);stone.scale.set(1,1.2+random()*.45,1);stone.rotation.y=random()*6;stone.castShadow=true;
 if(!occupied.has(`${t.x},${t.z}`)&&Math.abs(t.x)>2&&random()>.55){const tree=makeTree(t.x*2+(random()-.5)*.5,t.y,t.z*2,.55+random()*.6,this.group);model.decorations.push({x:tree.position.x,y:tree.position.y,z:tree.position.z});}else if(random()>.55){for(let j=0;j<3;j++){const grass=new THREE.Mesh(new THREE.ConeGeometry(.18,.55,4),material(0x6a9469));at(grass,t.x*2+(random()-.5)*1.6,t.y+.25,t.z*2+(random()-.5)*1.6,this.group);}}}
 if(!t.bridge&&random()>.96&&!occupied.has(`${t.x},${t.z}`)){const crack=line([[-.5,.013,-.6],[0,.015,-.15],[-.2,.015,.3],[.45,.015,.6]],0x83988b,.012);at(crack,t.x*2,t.y,t.z*2,this.group);}}
 for(const w of l.walls||[]){const g=new THREE.Group();const y=model.height(w.x,w.z);at(g,w.x*2,y,w.z*2,this.group);at(box(1.88,w.h,1.88,w.phase?0x67b9bc:0xc1c4b3),0,w.h/2,0,g);at(box(2.02,.18,2.02,0xe1d9c0),0,w.h,0,g);at(box(2,.18,2,0x9da890),0,.09,0,g);for(let i=0;i<2;i++)at(box(1.9,.028,1.9,0xa1ad9d),0,.8+i*.9,0,g);if(w.phase){const r=ring(.42,.045,0x68f0df);at(r,0,1.4,1,g);}this.wallMeshes.push({w,g});}
 for(const gate of l.gates||[]){const g=new THREE.Group();at(g,gate.x*2,model.height(gate.x,gate.z),gate.z*2,this.group);for(const x of [-.91,.91])at(box(.18,3,.35,0x798f87),x,1.5,0,g);at(box(2.05,.23,.45,0xd3ccae),0,3,0,g);const bars=box(1.7,2.8,.2,0x61baae,{transparent:true,opacity:.55,emissive:0x49b9a9,emissiveIntensity:.6});at(bars,0,1.4,0,g);this.gateMeshes.push({gate,g,bars});}
 for(const c of model.cubes){const g=makeCube(c.type);at(g,c.x*2,model.height(c.x,c.z),c.z*2,this.group);this.cubeMeshes.set(c.id,g);}
 for(const p of l.plates||[]){const g=new THREE.Group();at(g,p.x*2,model.height(p.x,p.z)+.025,p.z*2,this.group);at(cyl(.83,.065,0x506e70),0,0,0,g);at(cyl(.63,.08,0x7d9c92),0,.015,0,g);const color=p.phase?0x57e2d7:p.id==='beat'||l.id===7?0xef9bbd:l.id===5||l.id===9||l.id===10&&p.id!=='phase'?0xc9a0f5:0xf6c380;const r=ring(.69,.035,color);r.rotation.x=-Math.PI/2;at(r,0,.065,0,g);const dot=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,.05,4),glow(color));at(dot,0,.075,0,g);for(let i=0;i<4;i++){const m=box(.06,.02,.18,color);m.rotation.y=i*Math.PI/2;at(m,Math.sin(i*Math.PI/2)*.94,.015,Math.cos(i*Math.PI/2)*.94,g);}this.plateMeshes.push({p,g,r,dot,color});}
 for(const s of l.sockets||[]){const r=ring(.7,.012,0x8fa6a2);r.rotation.x=-Math.PI/2;at(r,s[0]*2,model.height(...s)+.022,s[1]*2,this.group);}
 for(const kind of ['sources','contacts','lasers','receivers'])for(const n of l[kind]||[]){const g=new THREE.Group();at(g,n.x*2,model.height(n.x,n.z),n.z*2,this.group);at(cyl(.6,.2,0x536e6b),0,.12,0,g);const stem=cyl(.31,kind==='lasers'?1.2:.65,0xd5d3bd,6);at(stem,0,kind==='lasers'?.6:.36,0,g);const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.28,1),glow(kind==='lasers'||kind==='receivers'?0xf9d18b:0x77ead0));at(orb,0,.8,0,g);const ring1=ring(.48,.045,0xa5c7b9);ring1.rotation.x=Math.PI/2;at(ring1,0,.8,0,g);this.nodeMeshes.push({n,orb,kind});}
 for(const lift of l.lifts||[]){const g=new THREE.Group();at(g,lift.x*2,0,lift.z*2,this.group);at(cyl(.95,.22,0x687f76),0,0,0,g);const r=ring(.85,.05,0x6aead4);r.rotation.x=Math.PI/2;at(r,0,.13,0,g);for(let i=0;i<4;i++){const stem=cyl(.045,lift.to+.5,0x658b87,6);at(stem,Math.sin(i*TAU/4)*1.08,lift.to/2,Math.cos(i*TAU/4)*1.08,this.group);stem.position.x+=lift.x*2;stem.position.z+=lift.z*2;}this.liftMeshes.push({lift,g,height:0});}
 const [px,pz]=l.portal,py=model.height(px,pz);this.portal=new THREE.Group();at(this.portal,px*2,py,pz*2,this.group);at(cyl(1.3,.23,0x778f86),0,.1,0,this.portal);at(cyl(1.1,.12,0xb6bfa9),0,.28,0,this.portal);
 const arch=new THREE.Mesh(new THREE.TorusGeometry(1.4,.18,4,32,Math.PI*1.64),material(0xd5d2b7));arch.rotation.z=-Math.PI*.32;at(arch,0,1.5,0,this.portal);arch.castShadow=true;const halo=ring(1.19,.055,0x79f2d5);at(halo,0,1.52,0,this.portal);this.portalHalo=halo;
 this.portalDisc=new THREE.Mesh(new THREE.CircleGeometry(1.13,48),new THREE.MeshBasicMaterial({color:0x64e1cb,side:THREE.DoubleSide,transparent:true,opacity:.07,depthWrite:false}));at(this.portalDisc,0,1.52,0,this.portal);for(let i=0;i<9;i++){const m=box(.15,.23,.2,0x587b74);m.rotation.z=-i*Math.PI/8;at(m,Math.cos(i*Math.PI/8)*1.41,1.5+Math.sin(i*Math.PI/8)*1.41,.18,this.portal);}
 this.portalOrbs=[];for(let i=0;i<14;i++){const p=new THREE.Mesh(new THREE.IcosahedronGeometry(.035,0),glow(0x89ffe2));this.portal.add(p);this.portalOrbs.push(p);}
 // Inlaid conduits make cause and effect visible without obscuring floor cells.
 for(const p of l.plates||[]){const target=(l.gates||[])[0]||{x:px,z:pz};const y=model.height(p.x,p.z)+.016;if(Math.abs(p.z-target.z)<9){const wire=line([[p.x*2,y,p.z*2],[p.x*2,y,target.z*2],[target.x*2,y,target.z*2]],p.phase?0x58a8a5:0xafb09a,.014);this.group.add(wire);}}
 for(const source of l.sources||[])for(const contact of l.contacts||[])this.group.add(line([[source.x*2,.025,source.z*2],[contact.x*2,.025,contact.z*2]],0x60b3a9,.02));
 this.batchFloors();this.update(0,null,null);}
 celebrate(){const group=new THREE.Group();this.group.add(group);const center=new THREE.Vector3(this.model.level.portal[0]*2,0,this.model.level.portal[1]*2);const motes=[];for(let i=0;i<120;i++){const p=new THREE.Mesh(new THREE.IcosahedronGeometry(.06+(i%3)*.025,0),glow(i%3===0?0xffcf82:0x8bffcf));group.add(p);motes.push(p);}const beacons=[];for(let i=0;i<8;i++){const a=i/8*TAU;const x=center.x+Math.cos(a)*16,z=center.z+Math.sin(a)*16;const r=ring(1.6,.045,0xa0ffd0);r.rotation.x=-Math.PI/2;at(r,x,2+i%3,z,group);beacons.push(r);const beam=line([[x,-3,z],[x,13,z]],0x9ae7c5,.045);group.add(beam);}this.sun.color.set(0xffd6a0);this.celebration={group,motes,beacons,center,start:this.time};}
 update(dt,player,held,nearest,menu=false,ending=false){this.time+=dt;const m=this.model,t=this.time;for(const {t:tile,m:mesh} of this.tileMeshes){if(tile.bridge){const active=!!m.flags[tile.bridge];mesh.material=material(active?0x7bbbae:0x80c8c3,{transparent:!active,opacity:active?1:.14,depthWrite:active});mesh.castShadow=active;}}
 for(const {w,g} of this.wallMeshes){if(w.phase){const inactive=m.flags[w.phase];g.children.forEach(o=>{if(o.material)o.material=material(inactive?0x73d3cd:0x7bada6,{transparent:true,opacity:inactive?.1:.84,depthWrite:!inactive});});}}
 for(const {gate,bars} of this.gateMeshes){const open=m.all(gate.needs);bars.scale.y=THREE.MathUtils.lerp(bars.scale.y,open?.02:1,Math.min(1,dt*9));bars.position.y=2.8-bars.scale.y*1.4;}
 for(const c of m.cubes){const g=this.cubeMeshes.get(c.id);const target=new THREE.Vector3(c.x*2,m.height(c.x,c.z),c.z*2);g.position.lerp(target,Math.min(1,dt*18||1));g.rotation.y=THREE.MathUtils.lerp(g.rotation.y,c.rot*Math.PI/2,Math.min(1,dt*13||1));g.userData.selection.visible=held===c.id||nearest===c.id;g.userData.selection.material.color.set(held===c.id?0x85ffe2:0xfff4ce);if(c.type==='echo')g.userData.core.material=material(m.echo.playing?0xb2709c:0x466b74);}
 for(const {p,r,dot,color} of this.plateMeshes){r.material=m.flags[p.id]?glow(color):material(color,{emissive:color,emissiveIntensity:.25});dot.scale.setScalar(m.flags[p.id]?1.5:1);}
 for(const {n,orb,kind} of this.nodeMeshes){const on=kind==='sources'||kind==='lasers'?m.all(n.needs):m.flags[n.id];orb.material=on?glow(kind==='receivers'||kind==='lasers'?0xf4d598:0x7bf9d5):material(0x587f7c);orb.rotation.y=t*.5;}
 for(const l of this.liftMeshes){const target=m.all(l.lift.needs)?(Math.sin(m.clock*.8-Math.PI/2)+1)/2*l.lift.to:0;l.height=THREE.MathUtils.damp(l.height,target,7,dt);l.g.position.y=l.height;}
 this.portalHalo.material=m.ready?glow(0x80fbd5):material(0x799e97,{emissive:0x65ac9e,emissiveIntensity:.22});this.portalDisc.material.opacity=m.ready?.23+Math.sin(t*2)*.06:.025;this.portalDisc.rotation.z=t*.1;this.portalOrbs.forEach((p,i)=>{p.visible=m.ready||menu;p.position.set(Math.cos(t*.6+i/14*TAU)*(1.12+Math.sin(t+i)*.05),1.52+Math.sin(t*.6+i/14*TAU)*1.12,.08+Math.sin(t+i)*.2);});
 const rayKey=JSON.stringify(m.rays);if(rayKey!==this.rayKey){this.rayKey=rayKey;this.clearGroup(this.rayGroup);for(const r of m.rays){const y=m.height(r.x,r.z)+.8;this.rayGroup.add(line([[r.x*2,y,r.z*2],[r.nx*2,y,r.nz*2]],0xffd996,.037));}}
 // Pair tether and reflector orientation preview.
 const linkKey=m.cubes.filter(c=>c.type==='linked'||c.id===held&&c.type==='reflector').map(c=>{const p=this.cubeMeshes.get(c.id).position;return c.id+':'+p.x.toFixed(2)+','+p.z.toFixed(2)+','+c.rot;}).join('|');if(linkKey!==this.linkKey){this.linkKey=linkKey;this.clearGroup(this.linkGroup);const pair=m.cubes.filter(c=>c.type==='linked');if(pair.length===2){const a=this.cubeMeshes.get(pair[0].id).position,b=this.cubeMeshes.get(pair[1].id).position;this.linkGroup.add(line([[a.x,a.y+1.65,a.z],[(a.x+b.x)/2,Math.max(a.y,b.y)+2.25,(a.z+b.z)/2],[b.x,b.y+1.65,b.z]],0xd5b7fa,.018));}
 const selected=m.cubes.find(c=>c.id===held);if(selected?.type==='reflector'){const a=this.cubeMeshes.get(selected.id).position,dir=selected.rot%2===0?-1:1;const color=0xa9ebff;this.linkGroup.add(line([[a.x-1.5,a.y+1.65,a.z],[a.x,a.y+1.65,a.z],[a.x,a.y+1.65,a.z+dir*1.5]],color,.025));const arrow=new THREE.Mesh(new THREE.ConeGeometry(.12,.35,6),glow(color));arrow.rotation.x=dir*Math.PI/2;at(arrow,a.x,a.y+1.65,a.z+dir*1.55,this.linkGroup);}
 }if(player){this.robot.position.copy(player.pos);this.robot.rotation.y=THREE.MathUtils.lerp(this.robot.rotation.y,player.facing,Math.min(1,dt*14));const speed=player.moving?1:0;this.robot.userData.body.position.y=Math.sin(t*(speed?12:2))*(speed?.035:.016);this.robot.userData.limbs.forEach((l,i)=>{l.rotation.x=Math.sin(t*12+i%2*Math.PI+(i>1?Math.PI:0))*.5*speed;});}
 this.clouds.forEach((c,i)=>{c.position.x+=dt*(.09+i%3*.02);if(c.position.x>95)c.position.x=-95;});this.particles.rotation.y=t*.007;if(this.celebration){const c=this.celebration,u=t-c.start;c.motes.forEach((p,i)=>{const a=i*2.399+u*.22,r=2+(i%19)*.7;p.position.set(c.center.x+Math.cos(a)*r,(u*1.4+i*.23)%16,c.center.z+Math.sin(a)*r);});c.beacons.forEach((p,i)=>{p.rotation.z=u*.2;p.position.y=2+i%3+Math.sin(u+i)*.3;});}if(ending){this.backdrop.children.forEach((g,i)=>{if(i>31)g.position.y+=Math.sin(t+i)*dt*.3;});this.portal.scale.setScalar(1+Math.sin(t)*.025);}
 }
 render(){this.renderer.render(this.scene,this.camera);}
}
